CREATE SCHEMA IF NOT EXISTS financialcontrol;

GRANT USAGE ON SCHEMA financialcontrol TO anon, authenticated, service_role;

GRANT ALL ON ALL TABLES IN SCHEMA financialcontrol TO anon, authenticated, service_role;

GRANT ALL ON ALL ROUTINES IN SCHEMA financialcontrol TO anon, authenticated, service_role;

GRANT ALL ON ALL SEQUENCES IN SCHEMA financialcontrol TO anon, authenticated, service_role;

-- Permissões padrão para futuras tabelas
ALTER DEFAULT PRIVILEGES FOR ROLE postgres IN SCHEMA financialcontrol 
GRANT ALL ON TABLES TO anon, authenticated, service_role;

ALTER DEFAULT PRIVILEGES FOR ROLE postgres IN SCHEMA financialcontrol 
GRANT ALL ON ROUTINES TO anon, authenticated, service_role;

ALTER DEFAULT PRIVILEGES FOR ROLE postgres IN SCHEMA financialcontrol 
GRANT ALL ON SEQUENCES TO anon, authenticated, service_role;



CREATE TABLE financialcontrol.category (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    description TEXT NOT NULL
);

CREATE TABLE financialcontrol.transaction (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    date TIMESTAMP WITHOUT TIME ZONE NOT NULL,
    credit_card TEXT NOT NULL,
    value NUMERIC NOT NULL,
    description TEXT NOT NULL,
    category_id BIGINT NULL REFERENCES financialcontrol.category(id)
);

CREATE TABLE financialcontrol.credit_card_closing_date (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    closing_date INT NOT NULL,
    best_day_to_buy INT NOT NULL,
    bank_name TEXT NOT NULL
);


ALTER TABLE financialcontrol.category DISABLE ROW LEVEL SECURITY;
ALTER TABLE financialcontrol.transaction DISABLE ROW LEVEL SECURITY;
ALTER TABLE financialcontrol.credit_card_closing_date DISABLE ROW LEVEL SECURITY;

CREATE OR REPLACE FUNCTION financialcontrol.getcategorybytransactiondescription(
  transactiondescription text
)
RETURNS TABLE (id bigint, description text)
LANGUAGE plpgsql
AS $$
BEGIN
  RETURN QUERY
  SELECT c.id, c.description
  FROM financialcontrol.category c
  INNER JOIN financialcontrol.transaction t ON t.category_id = c.id
  WHERE LOWER(t.description) LIKE '%' || LOWER(transactiondescription) || '%'
  LIMIT 1;
END;
$$;

CREATE OR REPLACE FUNCTION financialcontrol.get_transactions_by_closing_period(reference_date timestamp)
RETURNS SETOF financialcontrol.transaction
LANGUAGE plpgsql
AS $$
BEGIN
  RETURN QUERY
  SELECT t.id, t.date, t.credit_card, t.value,t.description, t.category_id, t.parcel_number
  FROM financialcontrol.transaction t
  INNER JOIN financialcontrol.credit_card_closing_date cc ON LOWER(t.credit_card) = LOWER(cc.bank_name)
  WHERE t.date >= (date_trunc('month', reference_date) + (cc.best_day_to_buy - 1 || ' days')::interval - interval '1 month')
    AND t.date < (date_trunc('month', reference_date) + (cc.best_day_to_buy - 1 || ' days')::interval + interval '1 month')
  ORDER BY t.id DESC;
END;
$$;